---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Scarlett Guang, Liam, Atticus, Taichit"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")


# Member 4 (pair 2) write code to load File 2 data here:
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")

# Member 1 (pair 1) write code to load File 3 data here:
data3 <- read_tsv("data/UN_country_population.tsv")



# Member 3 (pair 2) write code to load File 4 data here:
data4 <- read_excel("data/UN_country_region.xlsx")



```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':

plastic_data_all <- data1


# Member 4 (pair 2) write code to join your data to 'plastic_data_all':

data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")
plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")


# Member 1 (pair 1) write code to join your data to 'plastic_data_all':
plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")



# Member 3 (pair 2) write code to join your data to 'plastic_data_all':

data4 <- read_excel("data/UN_country_region.xlsx")
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'

plastic_data_all |> head(n = 10)

```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1
plastic_data_all |> 
count(region, sort = TRUE)
  
  


```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3
#By using left_join to gather the data into plastic_data_all
plastic_data_all<-left_join(data1,data2,by=c("name","code"))%>%
   mutate(
          pct_mismanged_plastic_ocean=mismanaged_plastic_ocean/mismanaged_plastic*100)%>%
          left_join(data4,by="code")%>%
#delete the external row name.y
select(-name.y)
#second part,find a median,(na.rm=TRUE)if I added it,filter(code=="SOM") is useless.
plastic_data_all %>%
group_by(region)%>%
summarise(median_pct_mismanaged_plastic_ocean= median(pct_mismanged_plastic_ocean))
#third part
plastic_data_all %>%
filter(code=="SOM")
#last part,add given code,arrange and output the final region.
plastic_data_all%>%
  drop_na(pct_mismanged_plastic_ocean)%>%
  group_by(region)%>%
  summarise(median_pct=median(pct_mismanged_plastic_ocean))%>%
arrange(median_pct)%>%
slice(1)

#I have used AI tool for finding dplyr verbs 'slice' to output the region, and skipping name.y（the code"select(-name.y).

#if my code has any contradictions with yours, please mentioned it and push.Or you can send an email to s2937668@ed.ac.uk to let me know.Thank you.

  
```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
